config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :tags, only: [:index, :show], param: :tag_name

  namespace :projects do
    resources :newest, only: :index
    resources :ranking, only: :index
  end

  resources :projects, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy], module: :projects
    resources :comments, only: :create, module: :projects
  end

  root to: "projects/ranking#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :project
  enum status: %i(main sub)
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :project, counter_cache: :likes_count
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :delete_all
  has_many :likes, dependent: :destroy
  has_many :comments
  accepts_nested_attributes_for :images, reject_if: :reject_images
  validates_presence_of :title, :catch_copy, :concept

  acts_as_taggable

  def reject_images(attributed)
    attributed['image'].blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:nickname, :member, :work, :profile, :avatar)
  end
end

app/controllers/projects/comments_controller.rb
class Projects::CommentsController < ApplicationController
  def create
  Comment.create(comment_params)
  @project = Project.find(params[:project_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(project_id: params[:project_id], user_id: current_user.id)
  end
end

app/controllers/projects/likes_controller.rb
class Projects::LikesController < ApplicationController
  before_action :set_likes, only: [:create, :destroy]
  before_action :find_likes, only: [:create, :destroy]

  def create
    @like = current_user.likes.create(project_id: params[:project_id])
  end

  def destroy
    @like = current_user.likes.find_by(project_id: params[:project_id])
    @like.destroy
  end

  private
  def set_likes
    @project = Project.find(params[:project_id])
  end

  def find_likes
    @likes = Like.where(project_id: params[:project_id])
  end
end

app/controllers/projects/newest_controller.rb
class Projects::NewestController < ApplicationController
  def index
    @projects = Project.includes(:user).page(params[:page]).per(8).order("created_at DESC")
  end
end

app/controllers/projects/ranking_controller.rb
class Projects::RankingController < ApplicationController
  def index
    @ranking_projects = Project.includes(:user).page(params[:page]).per(8)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def show
    @comment = Comment.new(project_id: @project)
    @like = current_user.likes.find_by(project_id: @project)
    @tags = @project.tag_list
  end

  def new
    @project = Project.new
    @project.images.build
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to root_path, notice: 'プロトタイプを更新しました'
    else
      render :edit
    end
  end

  def destroy
    if @project.user_id == current_user.id
      @project.destroy
      redirect_to root_path, notice: 'プロトタイプを削除しました'
    end
  end

  private
  def project_params
    params.require(:project).permit(:catch_copy, :title, :concept, images_attributes: [:id, :image, :status]).merge(user_id: current_user.id, tag_list: params[:tag_list])
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @projects = Project.includes(:user).tagged_with(params[:tag_name])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit]

  def show
    @projects = @user.projects.page(params[:page]).per(8)
  end

  def edit
  end

  def update
    current_user.update(update_params)
    redirect_to action: :show
  end

  private
  def update_params
    params.require(:user).permit(:nickname, :member, :work, :profile, :avatar, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def like_user
    current_user.likes
  end
end

app/helpers/projects/newest_helper.rb
module Projects::NewestHelper
end

app/helpers/projects/ranking_helper.rb
module Projects::RankingHelper
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      //not login
      - unless user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path
      //login
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{ aria: { expanded: "false"}, data: { toggle: "dropdown" }, href: "#", role: "button"}
              = current_user.nickname
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Profile Edit', edit_user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_project_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", http: {equiv: "Content-Type"}}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data: {turbolinks: {track: true}}
    = javascript_include_tag 'application', data: {turbolinks: {track: true}}
    = csrf_meta_tags
  %body
    - flash.each do |key, value|
      = content_tag(:div, value)
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/projects/_project.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && current_user.id == project.user_id
    .dropdown.drop_menu_location
      %button.btn.btn-default{ id: "dropdownMenu", type: "button",  data: { toggle: "dropdown" } } ACTION
      %ul.dropdown-menu{ aria: {labelledby: "dropdownMenu1"} }
        %li
          =link_to "Delete", project_path(project), rel: "nofollow", data: {method: "delete"}
        %li
          =link_to "Edit", edit_project_path(project)
  .thumbnail#content
    = link_to image_tag("#{project.images.main.first.image}"), project_path(project)
    .caption
      %h3
        = project.title
      .proto-meta
        .proto-user
          = link_to "by #{project.user.nickname}", user_path(project.user)
        .proto-posted
          = project.created_at.strftime("%b %d")
      %ul.proto-tag-list.list-inline
        - project.tags.each do |tag|
          %li
            = link_to tag, tag_path(tag.name), class: "btn btn-default"

app/views/projects/comments/_comment.html.haml
.col-md-8#comment_area
  .media
    .media-left
      = link_to image_tag("#{comment.user.avatar}", alt: "64x64", style: "width: 64px; height: 64px;", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", class: "media-object"), user_path(comment.user)
    .media-body
      %h4.media-heading#top-aligned-media
        = link_to "#{comment.user.nickname}", user_path(comment.user), class: "anchorjs-link"
      %p
        = comment.comment

app/views/projects/comments/create.js.erb
$('#comment_field').val('');
$('#comment_list').html(
  '<%= j(render partial: 'projects/comments/comment', collection: @project.comments) %>')
$('#comments_counter').html('(<%= @project.comments.count %>)')

app/views/projects/edit.html.haml
- if @project.errors.any?
  .error_explanation
    %h2
      = @project.errors.count
      件のエラーが発生しました
    %ul
      - @project.errors.full_messages.each do |message|
        %li
          = message
.container.proto-new
  = form_for(@project) do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "Title", autofocus: true, required: true, class: "proto-new-title"
      .row
        .col-md-12
          .cover-image-upload#edit-main-image
            = f.fields_for  :images, @project.images.main do |i|
              = i.file_field :image
              = i.hidden_field :status, value: "main"
        .col-md-12
          %ul.proto-sub-list.list-group
            = f.fields_for :images, @project.images.sub do |i|
              %li.list-group-item.col-md-4
                .image-upload#edit-sub1-image
                  = i.file_field :image
                  = i.hidden_field :status, value: "sub"
            = f.fields_for :images, @project.images.sub do |i|
              %li.list-group-item.col-md-4
                .image-upload#edit-sub2-image
                  = i.file_field :image
                  = i.hidden_field :status, value: "sub"
            %li.list-group-item.col-md-4
              .image-upload-plus
                %span +
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4"
        .col-md-12
          %h4 Tag List
          .row
            = form_for(@project) do |f|
              .col-md-3
                = text_field_tag "[tag_list][]", "", placeholder: "Web Design"
              .col-md-3
                = text_field_tag "[tag_list][]", "", placeholder: "UI"
              .col-md-3
                = text_field_tag "[tag_list][]","", placeholder: "Application"
      .row.text-center.proto-btn
        = f.submit :Publish, class: "btn btn-lg btn-primary btn-block"

app/views/projects/likes/_like.html.haml
- if user_signed_in?
  -if like_user.exists?(project_id: @project)
    = button_to project_like_path(@project, @like), method: :delete, class: "btn btn-default decrement-button", remote: true do
      = image_tag("icon_heart_red.svg")
      LIKE
      %span.num
        = @project.likes.count
  - else
    = button_to project_likes_path(@project), method: :post, class: "btn btn-default increment-button", remote: true do
      = image_tag("icon_heart.svg")
      LIKE
      %span.num
        = @project.likes.count

app/views/projects/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'projects/likes/like') %>");

app/views/projects/likes/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'projects/likes/like') %>");

app/views/projects/new.html.haml
- if @project.errors.any?
  .error_explanation
    %h2
      = @project.errors.count
      件のエラーが発生しました
    %ul
      - @project.errors.full_messages.each do |message|
        %li
          = message
.container.proto-new
  = form_for(@project) do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, placeholder: "Title", autofocus: true, required: true, class: "proto-new-title"
      .row
        .col-md-12
          .cover-image-upload#new-main-image
            = f.fields_for :images do |i|
              = i.file_field :image
              = i.hidden_field :status, value: "main"
        .col-md-12
          %ul.proto-sub-list.list-group
            = f.fields_for :images do |i|
              %li.list-group-item.col-md-4
                .image-upload#new-sub1-image
                  = i.file_field :image
                  = i.hidden_field :status, value: "sub"
            = f.fields_for :images do |i|
              %li.list-group-item.col-md-4
                .image-upload#new-sub2-image
                  = i.file_field :image
                  = i.hidden_field :status, value: "sub"
            %li.list-group-item.col-md-4
              .image-upload-plus
                %span +
      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, placeholder: "Concept", cols: "30", rows: "4"
        .col-md-12
          %h4 Tag List
          .row
            = form_for(@project) do |f|
              .col-md-3
                = text_field_tag "[tag_list][]", "", placeholder: "Web Design"
              .col-md-3
                = text_field_tag "[tag_list][]", "", placeholder: "UI"
              .col-md-3
                = text_field_tag "[tag_list][]","", placeholder: "Application"
      .row.text-center.proto-btn
        = f.submit :Publish, class: "btn btn-lg btn-primary btn-block"

app/views/projects/newest/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{ role: "presentation" }
          = link_to "Popular PROTO", root_path
        %li.active{ role: "presentation" }
          = link_to "Newest PROTO", projects_newest_index_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: "projects/project", collection: @projects

.text-center
  %ul.pagination
    %li.active
      = paginate @projects

app/views/projects/ranking/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          = link_to "Popular PROTO", root_path
        %li{ role: "presentation" }
          = link_to "Newest PROTO", projects_newest_index_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: "projects/project", collection: @ranking_projects

.text-center
  %ul.pagination
    %li.active
      = paginate @ranking_projects

app/views/projects/show.html.haml
%p{ id: "notice" }
= notice
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag("#{@project.user.avatar}", alt: "64×64",   data: { holder: { rendered: "true" } }, data:  { src: "holder.js/64x64"}, style: "width: 64px; height: 64px;", class: "media-object"), user_path(@project.user)
        .media-body
          %h4#top-aligned-media.media-heading
            = @project.title
          .proto-user
            = link_to "by #{@project.user.nickname}", user_path(@project.user)
            %span.degree
              = @project.user.member

    .col-md-6.clearfix#like-button
      = render partial: "projects/likes/like"
  .row
    .col-md-9
      = image_tag("#{@project.images.main.first.image}", class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
      - @project.images.sub.each do |sub|
        %li.list-group-item
          = image_tag("#{sub.image}", class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @project.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @project.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @tags.each do |tag|
          %li
            = link_to tag, tag_path(tag), class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num#comments_counter
        (#{@project.comments.count})
    .col-md-8#comment_area
      #comment_list
        = render partial: "projects/comments/comment", locals: { comment: @comment }, collection: @project.comments
      - if user_signed_in?
        = form_for [@project, @comment], class: "form-inline", role: "form", remote: true do |f|
          %h4
            Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :comment, placeholder: "Your comments", rows: "3", class: "form-control", id: "comment_text"
            .form-group.col-md-2
              = f.submit "Comment", class: "btn btn-primary"

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2 Tags list
      %ul
        - @tags.each do |tag|
          %li.col-md-4
            = link_to "#{tag.name}", tag_path(tag.name), class: "btn btn-default"

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          = link_to "Popular PROTO", root_path
        %li{ role: "presentation" }
          = link_to "Newest PROTO", projects_newest_index_path
      = link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    - @projects.each do |project|
      .col-sm-4.col-md-3.proto-content
        - if user_signed_in? && current_user.id == project.user_id
          .dropdown.drop_menu_location
            %button.btn.btn-default{ id: "dropdownMenu", type: "button",  data: { toggle: "dropdown" } } ACTION
            %ul.dropdown-menu{ aria: {labelledby: "dropdownMenu1"} }
              %li
                =link_to "Delete", project_path(project), rel: "nofollow", data: {method: "delete"}
              %li
                =link_to "Edit", edit_project_path(project)
        .thumbnail
          = link_to image_tag("#{project.images.main.first.image}"), project_path(project)
          .caption
            %h3
              = project.title
            .proto-meta
              .proto-user
                = link_to "by #{project.user.nickname}", user_path(project.user)
              .proto-posted
                = project.created_at.strftime("%b %d")
            %ul.proto-tag-list.list-inline
              - project.tags.each do |tag|
                %li
                  = link_to tag, tag_path(tag.name), class: "btn btn-default"

app/views/users/edit.html.haml
.container.user-new
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :nickname, placeholder: "nickname", autofocus: true, required: true
            .user-image.col-md-2#edit-user-avatar{ style: 'background-image: ' }
              %button.btn.btn-primary Change image
              = f.file_field :avatar, required: true
          = f.email_field :email, placeholder: "E-Mail", class: "user-email"
          = f.password_field :password, placeholder: "Password", class: "user-password", required: true
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :member, placeholder: "Member", required: true
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Profile", required: true
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :work, placeholder: "work", required: true
      .row.text-center.user-btn
        = f.submit :Save, class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar, alt: "64×64", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.nickname
          %span.label.label-default.project-number
            = @user.projects.count
            %i Projects
        .proto-user
          %span.degree
            = @user.member
        .row
          .col-md-6
            %h4 Profile
            %p
              = @user.profile
          .col-md-6
            %h4 Work
            %p
              = @user.work
.container.proto-list
  .row
    = render partial: "projects/project", collection: @projects

.text-center
  = paginate @projects